addSbtPlugin("com.eed3si9n"       % "sbt-projectmatrix"             % "0.9.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.13.2")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.14")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.2.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.2.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"                  % "2.5.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"                  % "2.4")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"                       % "1.1.0")
